-- ============================================================
-- Wedring Matrimony — Caste data import (insert only)
-- Project ref: pcdtgwelrwyvtqixqufc
--
-- The unique constraint (castes_religion_id_name_key) already
-- exists on this table from the earlier run — do NOT run the
-- "alter table ... add constraint" statement again, it will
-- error with 42P07 "already exists". Just run the insert below.
-- ============================================================

insert into castes (religion_id, name)
select r.id, v.caste_name
from religions r
cross join (values
  ('Hindu', 'Adi Dravida'),
  ('Hindu', 'Agamudayar'),
  ('Hindu', 'Brahmin - Iyer'),
  ('Hindu', 'Chettiar'),
  ('Hindu', 'Devar/Thevar/Mukkulathor'),
  ('Hindu', 'Devendra Kula Vellalar'),
  ('Hindu', 'Gounder'),
  ('Hindu', 'Kongu Vellala Gounder'),
  ('Hindu', 'Mudaliar'),
  ('Hindu', 'Mudaliar - Senguntha'),
  ('Hindu', 'Nadar'),
  ('Hindu', 'Naicker'),
  ('Hindu', 'Naidu'),
  ('Hindu', 'Pillai'),
  ('Hindu', 'Scheduled Caste (SC)'),
  ('Hindu', 'Vanniyakullak Kshatriya'),
  ('Hindu', 'Vanniyar'),
  ('Hindu', 'Vellalar'),
  ('Hindu', 'Vishwakarma'),
  ('Hindu', 'Yadav'),
  ('Hindu', '24 Manai Telugu Chettiar'),
  ('Hindu', '96 Kuli Maratha'),
  ('Hindu', '96K Kokanastha'),
  ('Hindu', 'Adi Andhra'),
  ('Hindu', 'Adi Dharmi'),
  ('Hindu', 'Adi Karnataka'),
  ('Hindu', 'Agarwal'),
  ('Hindu', 'Agnikula Kshatriya'),
  ('Hindu', 'Agri'),
  ('Hindu', 'Ahir'),
  ('Hindu', 'Ahom'),
  ('Hindu', 'Ambalavasi'),
  ('Hindu', 'Arcot'),
  ('Hindu', 'Arekatica'),
  ('Hindu', 'Arora'),
  ('Hindu', 'Arunthathiyar'),
  ('Hindu', 'Arya Vysya'),
  ('Hindu', 'Aryasamaj'),
  ('Hindu', 'Ayyaraka'),
  ('Hindu', 'Badaga'),
  ('Hindu', 'Baghel/Pal/Gaderiya'),
  ('Hindu', 'Bahi'),
  ('Hindu', 'Baidya'),
  ('Hindu', 'Baishnab'),
  ('Hindu', 'Baishya'),
  ('Hindu', 'Bajantri'),
  ('Hindu', 'Balija'),
  ('Hindu', 'Balija - Naidu'),
  ('Hindu', 'Banayat Oriya'),
  ('Hindu', 'Banik'),
  ('Hindu', 'Baniya'),
  ('Hindu', 'Barai'),
  ('Hindu', 'Bari'),
  ('Hindu', 'Barnwal'),
  ('Hindu', 'Barujibi'),
  ('Hindu', 'Besta'),
  ('Hindu', 'Bhandari'),
  ('Hindu', 'Bhatia'),
  ('Hindu', 'Bhatraju'),
  ('Hindu', 'Bhavsar'),
  ('Hindu', 'Bhovi'),
  ('Hindu', 'Billava'),
  ('Hindu', 'Boya/Nayak/Naik'),
  ('Hindu', 'Boyer'),
  ('Hindu', 'Brahmbatt'),
  ('Hindu', 'Brahmin - Anavil'),
  ('Hindu', 'Brahmin - Audichya'),
  ('Hindu', 'Brahmin - Barendra'),
  ('Hindu', 'Brahmin - Bhatt'),
  ('Hindu', 'Brahmin - Bhumihar'),
  ('Hindu', 'Brahmin - Brahmbhatt'),
  ('Hindu', 'Brahmin - Dadhich/Dadheech'),
  ('Hindu', 'Brahmin - Daivadnya'),
  ('Hindu', 'Brahmin - Danua'),
  ('Hindu', 'Brahmin - Deshastha'),
  ('Hindu', 'Brahmin - Dhiman'),
  ('Hindu', 'Brahmin - Dravida'),
  ('Hindu', 'Brahmin - Embrandiri'),
  ('Hindu', 'Brahmin - Goswami'),
  ('Hindu', 'Brahmin - Gour'),
  ('Hindu', 'Brahmin - Gowd Saraswat'),
  ('Hindu', 'Brahmin - Gujar Gour'),
  ('Hindu', 'Brahmin - Gurukkal'),
  ('Hindu', 'Brahmin - Halua'),
  ('Hindu', 'Brahmin - Havyaka'),
  ('Hindu', 'Brahmin - Himachali'),
  ('Hindu', 'Brahmin - Hoysala'),
  ('Hindu', 'Brahmin - Iyengar'),
  ('Hindu', 'Brahmin - Jangid'),
  ('Hindu', 'Brahmin - Jhadua'),
  ('Hindu', 'Brahmin - Jhijhotiya'),
  ('Hindu', 'Brahmin - Kanyakubja'),
  ('Hindu', 'Brahmin - Karhade'),
  ('Hindu', 'Brahmin - Kashmiri Pandit'),
  ('Hindu', 'Brahmin - Kokanastha'),
  ('Hindu', 'Brahmin - Kota'),
  ('Hindu', 'Brahmin - Kulin'),
  ('Hindu', 'Brahmin - Kumaoni'),
  ('Hindu', 'Brahmin - Madhwa'),
  ('Hindu', 'Brahmin - Maithili'),
  ('Hindu', 'Brahmin - Modh'),
  ('Hindu', 'Brahmin - Mohyal'),
  ('Hindu', 'Brahmin - Nagar'),
  ('Hindu', 'Brahmin - Namboodiri'),
  ('Hindu', 'Brahmin - Niyogi'),
  ('Hindu', 'Brahmin - Niyogi Nandavariki'),
  ('Hindu', 'Brahmin - Other'),
  ('Hindu', 'Brahmin - Paliwal'),
  ('Hindu', 'Brahmin - Panda'),
  ('Hindu', 'Brahmin - Pareek'),
  ('Hindu', 'Brahmin - Pushkarna'),
  ('Hindu', 'Brahmin - Rarhi'),
  ('Hindu', 'Brahmin - Rudraj'),
  ('Hindu', 'Brahmin - Sakaldwipi'),
  ('Hindu', 'Brahmin - Sanadya'),
  ('Hindu', 'Brahmin - Sanketi'),
  ('Hindu', 'Brahmin - Saraswat'),
  ('Hindu', 'Brahmin - Sarua'),
  ('Hindu', 'Brahmin - Saryuparin'),
  ('Hindu', 'Brahmin - Shivhalli'),
  ('Hindu', 'Brahmin - Shrimali'),
  ('Hindu', 'Brahmin - Smartha'),
  ('Hindu', 'Brahmin - Sri Vaishnava'),
  ('Hindu', 'Brahmin - Stanika'),
  ('Hindu', 'Brahmin - Tyagi'),
  ('Hindu', 'Brahmin - Vaidiki'),
  ('Hindu', 'Brahmin - Vaikhanasa'),
  ('Hindu', 'Brahmin - Velanadu'),
  ('Hindu', 'Brahmin - Viswabrahmin'),
  ('Hindu', 'Brahmin - Vyas'),
  ('Hindu', 'Brahmo'),
  ('Hindu', 'Buddar'),
  ('Hindu', 'Bunt (Shetty)'),
  ('Hindu', 'CKP'),
  ('Hindu', 'Chalawadi Holeya'),
  ('Hindu', 'Chambhar'),
  ('Hindu', 'Chandravanshi Kahar'),
  ('Hindu', 'Chasa'),
  ('Hindu', 'Chattada Sri Vaishnava'),
  ('Hindu', 'Chaudary'),
  ('Hindu', 'Chaurasia'),
  ('Hindu', 'Chekkala - Nair'),
  ('Hindu', 'Chennadasar'),
  ('Hindu', 'Cheramar'),
  ('Hindu', 'Chhetri'),
  ('Hindu', 'Chippolu/Mera'),
  ('Hindu', 'Devadiga'),
  ('Hindu', 'Devanga'),
  ('Hindu', 'Dhangar'),
  ('Hindu', 'Dheevara'),
  ('Hindu', 'Dhiman'),
  ('Hindu', 'Dhoba'),
  ('Hindu', 'Digambar'),
  ('Hindu', 'Dommala'),
  ('Hindu', 'Dusadh'),
  ('Hindu', 'Ediga'),
  ('Hindu', 'Ezhava'),
  ('Hindu', 'Ezhuthachan'),
  ('Hindu', 'Gabit'),
  ('Hindu', 'Ganakar'),
  ('Hindu', 'Gandla'),
  ('Hindu', 'Ganiga'),
  ('Hindu', 'Gatti'),
  ('Hindu', 'Gavali'),
  ('Hindu', 'Gavara'),
  ('Hindu', 'Ghumar'),
  ('Hindu', 'Goala'),
  ('Hindu', 'Goswami'),
  ('Hindu', 'Goud'),
  ('Hindu', 'Gowda'),
  ('Hindu', 'Gramani'),
  ('Hindu', 'Gudia'),
  ('Hindu', 'Gujjar'),
  ('Hindu', 'Gupta'),
  ('Hindu', 'Guptan'),
  ('Hindu', 'Gurjar'),
  ('Hindu', 'Halwai'),
  ('Hindu', 'Hegde'),
  ('Hindu', 'Helava'),
  ('Hindu', 'Hugar (Jeer)'),
  ('Hindu', 'Intercaste'),
  ('Hindu', 'Jaalari'),
  ('Hindu', 'Jaiswal'),
  ('Hindu', 'Jandra'),
  ('Hindu', 'Jangam'),
  ('Hindu', 'Jat'),
  ('Hindu', 'Jatav'),
  ('Hindu', 'Jetty Malla'),
  ('Hindu', 'Kachara'),
  ('Hindu', 'Kaibarta'),
  ('Hindu', 'Kakkalan'),
  ('Hindu', 'Kalar'),
  ('Hindu', 'Kalinga'),
  ('Hindu', 'Kalinga Vysya'),
  ('Hindu', 'Kalita'),
  ('Hindu', 'Kalwar'),
  ('Hindu', 'Kamboj'),
  ('Hindu', 'Kamma'),
  ('Hindu', 'Kamma Naidu'),
  ('Hindu', 'Kammala'),
  ('Hindu', 'Kaniyan'),
  ('Hindu', 'Kansari'),
  ('Hindu', 'Kanu'),
  ('Hindu', 'Kapu'),
  ('Hindu', 'Kapu Naidu'),
  ('Hindu', 'Karana'),
  ('Hindu', 'Karmakar'),
  ('Hindu', 'Kartha'),
  ('Hindu', 'Karuneegar'),
  ('Hindu', 'Kasar'),
  ('Hindu', 'Kashyap'),
  ('Hindu', 'Kavuthiyya/Ezhavathy'),
  ('Hindu', 'Kayastha'),
  ('Hindu', 'Khandayat'),
  ('Hindu', 'Khandelwal'),
  ('Hindu', 'Kharwar'),
  ('Hindu', 'Khatik'),
  ('Hindu', 'Khatri'),
  ('Hindu', 'Kirar'),
  ('Hindu', 'Koli'),
  ('Hindu', 'Koli Patel'),
  ('Hindu', 'Korama'),
  ('Hindu', 'Kori'),
  ('Hindu', 'Koshti'),
  ('Hindu', 'Krishnavaka'),
  ('Hindu', 'Kshatriya'),
  ('Hindu', 'Kshatriya - Bhavasar'),
  ('Hindu', 'Kshatriya/Raju/Varma'),
  ('Hindu', 'Kudumbi'),
  ('Hindu', 'Kulal'),
  ('Hindu', 'Kulalar'),
  ('Hindu', 'Kulita'),
  ('Hindu', 'Kumawat'),
  ('Hindu', 'Kumbara'),
  ('Hindu', 'Kumbhakar/Kumbhar'),
  ('Hindu', 'Kumhar'),
  ('Hindu', 'Kummari'),
  ('Hindu', 'Kunbi'),
  ('Hindu', 'Kurava'),
  ('Hindu', 'Kuravan'),
  ('Hindu', 'Kurmi'),
  ('Hindu', 'Kurmi Kshatriya'),
  ('Hindu', 'Kuruba'),
  ('Hindu', 'Kuruhina Shetty'),
  ('Hindu', 'Kurumbar'),
  ('Hindu', 'Kurup'),
  ('Hindu', 'Kushwaha'),
  ('Hindu', 'Lambadi/Banjara'),
  ('Hindu', 'Lambani'),
  ('Hindu', 'Leva Patil'),
  ('Hindu', 'Lingayath'),
  ('Hindu', 'Lohana'),
  ('Hindu', 'Lohar'),
  ('Hindu', 'Loniya/Lonia/Lunia'),
  ('Hindu', 'Lubana'),
  ('Hindu', 'Madhesiya'),
  ('Hindu', 'Madiga'),
  ('Hindu', 'Mahajan'),
  ('Hindu', 'Mahar'),
  ('Hindu', 'Mahendra'),
  ('Hindu', 'Maheshwari'),
  ('Hindu', 'Mahindra'),
  ('Hindu', 'Mahishya'),
  ('Hindu', 'Majabi'),
  ('Hindu', 'Mala'),
  ('Hindu', 'Malayalee Variar'),
  ('Hindu', 'Mali'),
  ('Hindu', 'Mallah'),
  ('Hindu', 'Mangalorean'),
  ('Hindu', 'Maniyani'),
  ('Hindu', 'Mannadiar'),
  ('Hindu', 'Mannan'),
  ('Hindu', 'Mapila'),
  ('Hindu', 'Marar'),
  ('Hindu', 'Maratha'),
  ('Hindu', 'Maratha - Gomantak'),
  ('Hindu', 'Maruthuvar'),
  ('Hindu', 'Marvar'),
  ('Hindu', 'Marwari'),
  ('Hindu', 'Matang'),
  ('Hindu', 'Maurya'),
  ('Hindu', 'Meda'),
  ('Hindu', 'Medara'),
  ('Hindu', 'Meena'),
  ('Hindu', 'Meenavar'),
  ('Hindu', 'Meghwal'),
  ('Hindu', 'Mehra'),
  ('Hindu', 'Menon'),
  ('Hindu', 'Meru Darji'),
  ('Hindu', 'Modak'),
  ('Hindu', 'Mogaveera'),
  ('Hindu', 'Monchi'),
  ('Hindu', 'Mudaliar - Arcot'),
  ('Hindu', 'Mudaliar - Saiva'),
  ('Hindu', 'Mudiraj'),
  ('Hindu', 'Munnuru Kapu'),
  ('Hindu', 'Muthuraja'),
  ('Hindu', 'Naagavamsam'),
  ('Hindu', 'Nagaralu'),
  ('Hindu', 'Nai'),
  ('Hindu', 'Naicken'),
  ('Hindu', 'Naik'),
  ('Hindu', 'Nair'),
  ('Hindu', 'Nair - Vaniya'),
  ('Hindu', 'Nair - Velethadathu'),
  ('Hindu', 'Nair - Vilakkithala'),
  ('Hindu', 'Namasudra'),
  ('Hindu', 'Nambiar'),
  ('Hindu', 'Nambisan'),
  ('Hindu', 'Namdev'),
  ('Hindu', 'Namosudra'),
  ('Hindu', 'Napit'),
  ('Hindu', 'Nayak'),
  ('Hindu', 'Nayaka'),
  ('Hindu', 'Neeli'),
  ('Hindu', 'Nhavi'),
  ('Hindu', 'OBC - Barber/Naayee'),
  ('Hindu', 'Oswal'),
  ('Hindu', 'Otari'),
  ('Hindu', 'Padmasali'),
  ('Hindu', 'Panchal'),
  ('Hindu', 'Pandaram'),
  ('Hindu', 'Panicker'),
  ('Hindu', 'Paravan'),
  ('Hindu', 'Parit'),
  ('Hindu', 'Parkava Kulam'),
  ('Hindu', 'Partraj'),
  ('Hindu', 'Pasi'),
  ('Hindu', 'Paswan'),
  ('Hindu', 'Patel'),
  ('Hindu', 'Patel - Desai'),
  ('Hindu', 'Patel - Dodia'),
  ('Hindu', 'Patel - Kadva'),
  ('Hindu', 'Patel - Leva'),
  ('Hindu', 'Patnaick'),
  ('Hindu', 'Patra'),
  ('Hindu', 'Patwa'),
  ('Hindu', 'Perika'),
  ('Hindu', 'Pisharody'),
  ('Hindu', 'Poduval'),
  ('Hindu', 'Poosala'),
  ('Hindu', 'Porwal'),
  ('Hindu', 'Prajapati'),
  ('Hindu', 'Pulaya'),
  ('Hindu', 'Raigar'),
  ('Hindu', 'Rajaka/Chakali/Dhobi'),
  ('Hindu', 'Rajbhar'),
  ('Hindu', 'Rajput'),
  ('Hindu', 'Rajput - Kumaoni'),
  ('Hindu', 'Rajput - Lodhi'),
  ('Hindu', 'Ramdasia'),
  ('Hindu', 'Ramgharia'),
  ('Hindu', 'Rauniyar'),
  ('Hindu', 'Ravidasia'),
  ('Hindu', 'Rawat'),
  ('Hindu', 'Reddiar'),
  ('Hindu', 'Reddy'),
  ('Hindu', 'Relli'),
  ('Hindu', 'SSK'),
  ('Hindu', 'Sadgop'),
  ('Hindu', 'Sagara - Uppara'),
  ('Hindu', 'Saha'),
  ('Hindu', 'Sahu'),
  ('Hindu', 'Saini'),
  ('Hindu', 'Saiva Vellala'),
  ('Hindu', 'Saliya'),
  ('Hindu', 'Sambava'),
  ('Hindu', 'Satnami'),
  ('Hindu', 'Savji'),
  ('Hindu', 'Scheduled Tribe (ST)'),
  ('Hindu', 'Senai Thalaivar'),
  ('Hindu', 'Sepahia'),
  ('Hindu', 'Setti Balija'),
  ('Hindu', 'Shah'),
  ('Hindu', 'Shilpkar'),
  ('Hindu', 'Shimpi'),
  ('Hindu', 'Sindhi - Bhanusali'),
  ('Hindu', 'Sindhi - Bhatia'),
  ('Hindu', 'Sindhi - Chhapru'),
  ('Hindu', 'Sindhi - Dadu'),
  ('Hindu', 'Sindhi - Hyderabadi'),
  ('Hindu', 'Sindhi - Larai'),
  ('Hindu', 'Sindhi - Lohana'),
  ('Hindu', 'Sindhi - Rohiri'),
  ('Hindu', 'Sindhi - Sehwani'),
  ('Hindu', 'Sindhi - Thatai'),
  ('Hindu', 'Sindhi-Amil'),
  ('Hindu', 'Sindhi-Baibhand'),
  ('Hindu', 'Sindhi-Larkana'),
  ('Hindu', 'Sindhi-Sahiti'),
  ('Hindu', 'Sindhi-Sakkhar'),
  ('Hindu', 'Sindhi-Shikarpuri'),
  ('Hindu', 'Somvanshi'),
  ('Hindu', 'Sonar'),
  ('Hindu', 'Soni'),
  ('Hindu', 'Sozhiya Vellalar'),
  ('Hindu', 'Sri Vaishnava'),
  ('Hindu', 'Srisayana'),
  ('Hindu', 'Subarna Banik'),
  ('Hindu', 'Sugali (Naika)'),
  ('Hindu', 'Sundhi'),
  ('Hindu', 'Surya Balija'),
  ('Hindu', 'Sutar'),
  ('Hindu', 'Suthar'),
  ('Hindu', 'Swakula Sali'),
  ('Hindu', 'Swarnakar'),
  ('Hindu', 'Tamboli'),
  ('Hindu', 'Tanti'),
  ('Hindu', 'Tantuway'),
  ('Hindu', 'Telaga'),
  ('Hindu', 'Teli'),
  ('Hindu', 'Thachar'),
  ('Hindu', 'Thakkar'),
  ('Hindu', 'Thakur'),
  ('Hindu', 'Thandan'),
  ('Hindu', 'Thigala'),
  ('Hindu', 'Thiyya'),
  ('Hindu', 'Thuluva Vellala'),
  ('Hindu', 'Tili'),
  ('Hindu', 'Togata'),
  ('Hindu', 'Turupu Kapu'),
  ('Hindu', 'Udayar'),
  ('Hindu', 'Urali Gounder'),
  ('Hindu', 'Urs'),
  ('Hindu', 'Vada Balija'),
  ('Hindu', 'Vadagalai'),
  ('Hindu', 'Vaddera'),
  ('Hindu', 'Vaduka'),
  ('Hindu', 'Vaish'),
  ('Hindu', 'Vaish - Dhaneshawat'),
  ('Hindu', 'Vaishnav'),
  ('Hindu', 'Vaishnav - Bhatia'),
  ('Hindu', 'Vaishnav - Vania'),
  ('Hindu', 'Vaishya'),
  ('Hindu', 'Vallala'),
  ('Hindu', 'Valluvan'),
  ('Hindu', 'Valmiki'),
  ('Hindu', 'Vanika Vyshya'),
  ('Hindu', 'Vaniya Chettiar'),
  ('Hindu', 'Vanjara'),
  ('Hindu', 'Vankar'),
  ('Hindu', 'Vannan'),
  ('Hindu', 'Vannar'),
  ('Hindu', 'Variar'),
  ('Hindu', 'Varshney'),
  ('Hindu', 'Veerashaiva'),
  ('Hindu', 'Velaan'),
  ('Hindu', 'Velama'),
  ('Hindu', 'Velar'),
  ('Hindu', 'Veluthedathu - Nair'),
  ('Hindu', 'Vettuva Gounder'),
  ('Hindu', 'Viswabrahmin'),
  ('Hindu', 'Vokkaliga'),
  ('Hindu', 'Vysya'),
  ('Hindu', 'Waada Balija'),
  ('Hindu', 'Yellapu')
) as v(religion_name, caste_name)
where r.name = v.religion_name
on conflict (religion_id, name) do nothing;